### ISSUE TITLE
After using `Skewness Balancing` filter the next one throws an error.

### ISSUE THREAD

**Issue by GwydionJon** [ssciwr/adaptivefiltering#275]
The error also freezes my jupyter lab console, so I can't look at it completely.

**Comment by dokempf** [comment]
Is that a pipeline with two stages? If so, what is the second one?

**Comment by GwydionJon** [comment]
no just one pipeline and after that another one.
I tried with three or four and all threw an error.

**Comment by dokempf** [comment]
Doesnt reproduce.
