### ISSUE TITLE
How to refer to the library in documentation

### ISSUE THREAD

**Issue by zaw-shinoto** [ssciwr/adaptivefiltering#278]
1. Do we call it 
    - adaptive filtering
    - Adaptive Filtering
    - `adaptive filtering`
2. Do we refer to it as a "library" exclusively?
3. If no capitals are used, how to we spell it at the beginning of a sentence:
    - The `adaptive filtering` library ...
    - Adaptive filtering...
    - `adaptive filtering`...
    - etc. ...

**Comment by dokempf** [comment]
After discussion this morning: We use `adaptivefiltering` (no space) everywhere
