### ISSUE TITLE
Can't diretly use widget output in same cell

### ISSUE THREAD

**Issue by GwydionJon** [ssciwr/adaptivefiltering#282]
`pipelines2 = list(af.select_pipelines_from_library())` returns an empty list.

while this works, when done in separate cells.
`pipelines2 = af.select_pipelines_from_library()`
`list(pipelines2)`

I'm guessing that in the first case the list conversion is done while the return proxy is still empty, thus I don't think one can avoid this. 
This behavior also breaks different apps.

Likely for the same reason `pipelines = pipelines+af.select_pipelines_from_library()` does not work, although a user might expect it to.

**Comment by dokempf** [comment]
The fact that these do not work make sense when knowing the inner workings of the `ObjectProxy` details. We have to trust the users to follow documented usage behaviours on this one.
