### ISSUE TITLE
Segmentation GeoJSON should contain human-readable filename

### ISSUE THREAD

**Issue by dokempf** [ssciwr/adaptivefiltering#317]
No-op, only for informational purpose.

**Comment by dokempf** [comment]
Once implemented, this TODO should also be resolved: https://github.com/ssciwr/adaptivefiltering/blob/main/adaptivefiltering/execute.py#L122

**Comment by GwydionJon** [comment]
I am not sure what you mean by filename, I would just use the filter title as a filename.
