### ISSUE TITLE
Geo coordinates to show

### ISSUE THREAD

**Issue by zaw-shinoto** [ssciwr/adaptivefiltering#75]
When showing maps, one might go for the usual `EPSG:4326` in the beginning, but different systems may be helpful if we get into small areas which show large deviation. 

Maybe, that Michael can judge whether he needed such functionality for his filtering, and @lrg-bhoefle should be able to comment on this as well. -- I will check for problems with `EPSG:4326` when I start with Jupyter notebooks and data sets from South Japan.

**Comment by dokempf** [comment]
The map implementation that we are using (`ipyleaflet`) is quite restrictive w.r.t. the CRS. So, any needs related to this would require substantial work on the technical side. Avoiding this is a high priority to me. I will close this now, please reopen once there is a use case that requires a solution.
