### ISSUE TITLE
ipyleaflet map missing map data on zoom

### ISSUE THREAD

**Issue by GwydionJon** [ssciwr/adaptivefiltering#88]
When using the pkgebk_all.las dataset one can not zoom in all the way without ipyleaflet switching from a satellite image to an error messag. This may be happening in different remote locations as well.

![Example_of_ipyLeaflet_Map_error](https://user-images.githubusercontent.com/35529247/145838490-ee474d53-3525-4755-99e1-5f6265d73145.png)

**Comment by dokempf** [comment]
This is a property of the used map. Not having the overlay layer be opaque by default is enough of a workaround IMO.

**Comment by GwydionJon** [comment]
it appears, that the Esri.WorldImagery we are using is the best supported map
